version: '3'
services:
  ethereum:
    image: ethereum/client-go
    volumes:
      - ./blockchains:/root/.ethereum
    ports:
      - "30303:30303"
      - "8545:8545"
    entrypoint: /geth --fast --cache=512 --rpc --rpcaddr "0.0.0.0"
